# File: .streamlit/secrets.toml
GOOGLE_API_KEY = "AIzaSyAdP2wPK0n-G03yO1YE60yE2NPMBo9sJSQ"
QDRANT_URL = "https://cd6d1bd4-f86a-4486-9b88-5d5870e152a5.europe-west3-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.erRi2rr3j-9QYSvjsMiQoc05EL4e-lLH5Qtu4Xwr92c"