[theme]
# Mengaktifkan base dark mode agar elemen default Streamlit menyesuaikan (grafik, peta, dll)
base = "dark"

# Warna utama (Tombol, Slider, Link aktif) - Warna Caramel/Golden Brown
primaryColor = "#D4A373"

# Warna latar belakang utama - Warna Espresso Gelap (Hampir hitam tapi kecoklatan)
backgroundColor = "#1E1614"

# Warna latar belakang sidebar & input box - Warna Dark Chocolate
secondaryBackgroundColor = "#2C221E"

# Warna teks utama - Warna Crema/Foam (Krem terang agar kontras)
textColor = "#E6D7C3"

# Font
font = "sans serif"